--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Todos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE DATABASE todo_mtp;

\c todo_mtp

CREATE TABLE public."Todos" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "IsDone" boolean NOT NULL,
    "DueDate" date DEFAULT '-infinity'::date NOT NULL,
    "Priority" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Todos" OWNER TO postgres;

--
-- Name: Todos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Todos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Todos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."Todos"
    ADD CONSTRAINT "PK_Todos" PRIMARY KEY ("Id");
